### ISSUE TITLE
Clone folder is repo name, does not match ~/spotify-muter-linux folder

### ISSUE THREAD

**Issue by smarkoco** [nisiddharth/Spotify-Ads-Muter-Linux#3]
I'm not sure if that's how it was before or if I broke something, but I just cloned this repo, and the folder had the same name as the repo, so the code doesn't run immediately 

Should we change the repo name or change the folder references to match the repo name? Haha

**Comment by nisiddharth** [comment]
Ohh, didn't even notice that :rofl: 

I guess we can leave it as such.

**Comment by smarkoco** [comment]
hah I think I had corrected that a long time ago, so had forgotten about that change 😅 just submitted the change
